name: Build and Package Snort

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22.4"

      - name: Install dependencies and build Snort
        run: |
          chmod +x /scripts/snort3.sh
          /scripts/snort3.sh

      - name: Create Debian package
        run: |
          cd /work/snort3-${SNORT_VER}/build
          sudo checkinstall --pkgname=snort3 --pkgversion=${SNORT_VER} --backup=no --deldoc=yes --fstrans=no --default

      - name: Upload Debian package
        uses: actions/upload-artifact@v2
        with:
          name: snort3-deb
          path: /work/snort3-${SNORT_VER}/build/snort3_${SNORT_VER}_amd64.deb

      - name: Publish to GitHub Packages
        run: |
          curl -u ${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }} \
            -H "Content-Type: $(file -b --mime-type /work/snort3-${SNORT_VER}/build/snort3_${SNORT_VER}_amd64.deb)" \
            --data-binary @/work/snort3-${SNORT_VER}/build/snort3_${SNORT_VER}_amd64.deb \
            "https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/latest/assets?name=snort3_${SNORT_VER}_amd64.deb"
