name: Build, Package, and Release Snort 3

on:
  push:
    branches:
      - "*"

permissions:
  contents: write

jobs:
  build:
    name: Build and Package Snort 3
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y git dpkg-dev

      - name: Build and Package Snort 3
        run: |
          ARCH=${{ matrix.arch }}
          bash ./scripts/snort3.sh
          mkdir -p /work/packages/$ARCH
          mv /work/*.deb /work/packages/$ARCH/

      - name: Upload packages as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: snort3-packages-${{ matrix.arch }}
          path: /work/packages/${{ matrix.arch }}

  deploy:
    name: Create GitHub Release and Upload Assets
    runs-on: ubuntu-latest
    needs: build
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Create a release
        id: release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Snort 3 Release
          draft: false
          prerelease: false

      - name: Create work directory
        run: sudo mkdir -p /work && sudo chmod -R 777 /work

      - name: Download amd64 packages
        uses: actions/download-artifact@v4
        with:
          name: snort3-packages-amd64
          path: /work/packages/amd64

      - name: Download arm64 packages
        uses: actions/download-artifact@v4
        with:
          name: snort3-packages-arm64
          path: /work/packages/arm64

      - name: List amd64 files
        run: ls -l /work/packages/amd64/

      - name: List arm64 files
        run: ls -l /work/packages/arm64/

      - name: Upload amd64 package to GitHub Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: /work/packages/amd64/snort3-amd64.deb
          asset_name: snort3-amd64.deb
          asset_content_type: application/octet-stream

      - name: Upload arm64 package to GitHub Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: /work/packages/arm64/snort3-arm64.deb
          asset_name: snort3-arm64.deb
          asset_content_type: application/octet-stream
