name: Build and Package Snort 3

on:
  push:
    branches:
      - "*"

jobs:
  build:
    name: Build and Package Snort 3
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y git dpkg-dev

      - name: Build Snort 3 and dependencies
        run: |
          ARCH=${{ matrix.arch }}
          bash ./scripts/snort3.sh
          mkdir -p /work/packages/$ARCH
          mv /work/*.deb /work/packages/$ARCH/

      - name: Package Snort 3 with dependencies
        run: |
          bash ./scripts/package_snort3.sh ${{ matrix.arch }}

      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: snort3-packages-${{ matrix.arch }}
          path: /work/packages/${{ matrix.arch }}

  deploy:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    needs: build
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Create work directory
        run: sudo mkdir -p /work && sudo chmod -R 777 /work

      - name: Download amd64 packages
        uses: actions/download-artifact@v4
        with:
          name: snort3-packages-amd64
          path: /work/packages/amd64

      - name: Download arm64 packages
        uses: actions/download-artifact@v4
        with:
          name: snort3-packages-arm64
          path: /work/packages/arm64

      - name: Publish packages
        run: |
          for ARCH in amd64 arm64; do
            cd /work/packages/$ARCH
            for file in *.deb; do
              curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Content-Type: $(file --mime-type -b $file)" \
                --data-binary @$file \
                "https://uploads.github.com/repos/ADORSYS-GIS/wazuh-snort/releases/assets?name=$(basename $file)"
            done
          done
