name: Build and Package Snort 3

on:
  push:
    branches:
      - "*"

jobs:
  build:
    name: Build and Package Snort 3
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y git dpkg-dev

    - name: Build and Package Snort 3
      run: |
        ARCH=${{ matrix.arch }}
        bash ./scripts/snort3.sh
        mkdir -p packages/$ARCH
        mv *.deb packages/$ARCH/
      
    - name: Upload packages
      uses: actions/upload-artifact@v3
      with:
        name: snort3-packages-${{ matrix.arch }}
        path: packages/${{ matrix.arch }}

  deploy:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download packages
      uses: actions/download-artifact@v3
      with:
        name: snort3-packages-amd64
        path: packages/amd64

    - name: Download packages
      uses: actions/download-artifact@v3
      with:
        name: snort3-packages-arm64
        path: packages/arm64

    - name: Publish .deb packages
      run: |
        for arch in amd64 arm64; do
          cd packages/$arch
          for deb in *.deb; do
            gh release upload --repo <YOUR_REPO> ${{ github.ref_name }} $deb --clobber
          done
        done
