name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl gnupg2 iproute2
        pip install pytest pytest-testinfra

    - name: Run Snort install script
      run: |
        sudo bash scripts/install.sh

    - name: Run tests
      run: |
        pytest scripts/tests/test_install.py
