name: Run Tests

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # Operating systems
        python-version: ['3.9']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Linux-specific steps
    - name: Install dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y curl gnupg2 iproute2
        pip install pytest pytest-testinfra

    - name: Install Wazuh agent (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | sudo apt-key add -
        echo "deb https://packages.wazuh.com/4.x/apt/ stable main" | sudo tee /etc/apt/sources.list.d/wazuh.list
        sudo apt-get update
        sudo apt-get install -y wazuh-agent

    - name: Run Snort install script (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo bash scripts/install.sh

    # Windows-specific steps
    - name: Install Wazuh agent (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        Invoke-WebRequest -Uri https://packages.wazuh.com/4.x/windows/wazuh-agent-4.9.0-1.msi -OutFile $env:TEMP\wazuh-agent.msi
        msiexec.exe /i $env:TEMP\wazuh-agent.msi /qn WAZUH_MANAGER='10.0.0.1' WAZUH_AGENT_NAME='test'

    - name: Install Snort (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        Start-Process powershell -ArgumentList "-File scripts/snort.ps1" -Verb RunAs

    # Running tests
    - name: Run tests (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo $(which pytest) -vv scripts/tests/test_linux.py

    - name: Run PowerShell tests (Windows)
      if: matrix.os == 'windows-latest'
      run:
        pwsh -File ${{ github.workspace }}/scripts/test_windows.ps1
