name: Create release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Generate script checksums
        run: |
          find scripts \( -path "scripts/tests" -o -path "scripts/tests/*" \) -prune -o -type f -exec sha256sum {} + > checksums.sha256
          cat checksums.sha256

      - name: Generate release notes (latest only)
        id: git_cliff
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --latest --strip header

      - name: Generate full CHANGELOG.md
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --output CHANGELOG.md

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          name: Release ${{ steps.get_version.outputs.VERSION }}
          files: checksums.sha256
          body: ${{ steps.git_cliff.outputs.content }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          git add CHANGELOG.md checksums.sha256
          git commit -m "chore: update CHANGELOG.md and checksums"

      - name: Create Pull Request to update CHANGELOG.md and checksums
        uses: peter-evans/create-pull-request@v8
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Update Changelog and checksums"
          body: |
            This PR updates the CHANGELOG.md and checksums.
            - Generated using git-cliff
            - Triggered by: ${{ github.event_name }}
          branch: update-changelog-${{ github.run_id }}
          base: main
          delete-branch: true
          labels: documentation, automated-pr