name: Snort Install Script Test

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl gnupg2 iproute2 net-tools 

    - name: Install BATS
      run: |
        git clone https://github.com/bats-core/bats-core.git /tmp/bats-core
        sudo /tmp/bats-core/install.sh /usr/local

    - name: Verify BATS installation
      run: which bats

    - name: Verify BATS installation
      run: which bats
            
    - name: Make test script executable
      run: chmod +x scripts/tests/test-script.bats

    - name: Run Bats tests
      run: |
        sudo bats scripts/tests/test-script.bats
