name: Snort Install Script Test

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Make install script executable
      run: chmod +x scripts/install.sh

    - name: Install Bats
      run: |
        sudo apt-get update
        sudo apt-get install -y bats

    - name: Run Bats tests
      run: |
        bats scripts/tests/test-script.bats
